
site_name: EPD Documentation
repo_name: "EPD-Docs"
repo_url: "https://github.com/rafabr34/EPD-Docs"



theme:
  name: "material"
  custom_dir: docs/custom_theme/
  palette:
    scheme: slate
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - abbr


nav:
    - Home: "index.md"
    - About:
        - "License": "EPDLicense.md"
        - "Release Notes": "release-notes.md"

    - Script-Hub:
      - Utilities:
        - EPD Explorer:
          - Luau-Match-Search: "HUB/Explorer/LuauMatchSearch.md"
          - RBX-Docs-WebScrapper: "HUB/Explorer/WebScrapper.md"


    - API:
      - EPD Enums/Info:
        - Useful CPU Features: "API/Enums/Hardware.md"


      - Libraries:

        - User Library:
          - "SetFPSLimit()": "API/UserLibrary/SetFPSLimit.md" 
          - "SendMessageBox()": "API/UserLibrary/SendMessageBox.md" 
          - "SendEPDPrompt()": "API/UserLibrary/SendEPDPrompt.md"

        - Instances:
          - "GetProperties()": "API/InstancesLibrary/GetProperties.md"
          - "ForceCreateInstance()": "API/InstancesLibrary/ForceCreateInstance.md"
          - "GetScriptRawByteCode()": "API/InstancesLibrary/GetScriptRawByteCode.md"
          - "PseudoRunLocalScript()": "API/InstancesLibrary/PseudoRunLocalScript.md"

        - Miscellaneous:
          - Random:
            - "TrueRandom()": "API/MiscLibraries/Random/TrueRandom.md"
          - Events:
            - "CreateSignal()": "API/MiscLibraries/Events/CreateSignal.md"
            - "FireSignal()": "API/MiscLibraries/Events/FireSignal.md"
            - "SetSignalBehavior()": "API/MiscLibraries/Events/SetSignalBehavior.md"

      #- EPD Events:

