
name: MkDocs Push

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installing Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        pip install requests

        pip install mkdocs-material
        pip install Pygments

    
     
    - name: MkDocs Build
      run: |
        mkdocs build --config-file mkdocs.yml
        
        
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: BuiltSite



    - name: Send Webhook
      run: |
        cat <<EOT >> WebhookSend.py
        import requests
        import json
        import time
        Data = {
          "username": "Deployed The Site",
          #"avatar_url": "https://i.imgur.com/4M34hi2.png",
          #"content": "",
          "embeds": [
            {
              "title": "EPD Docs Was Deployed",
              "url": "https://rafabr34.github.io/EPD-Docs/",
              "description": "Docs Site Deployed At " + time.strftime("%a, %d %b %Y %H:%M:%S", time.gmtime()),
              "color": 12912,
              "fields": [
                {
                  "name": "Docs Version:",
                  "value": "V" + "$GITHUB_RUN_NUMBER",
                },
                {
                  "name": "Commit Reason:",
                  "value": "${{ github.event.commits[0].message }}",
                },
              ],

            }
          ]
        }
        Result = requests.post("${{ secrets.DISCORD_DOCS_DEPLOYED_WEBHOOK }}",headers={"Content-Type":"application/json"},data=json.dumps(Data))
        print(Result.content)
        exit(0)
        EOT
        python WebhookSend.py
        rm WebhookSend.py


