
name: MkDocs Push

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3

    - name: Setting Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installing Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        pip install mkdocs-material
        pip install Pygments

        pip install requests
     
    - name: MkDocs Build
      run: |
        mkdocs build --config-file mkdocs.yml
        
        
    - name: Deploying Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: BuiltSite

    - name: Send Webhook
      env:
        DiscordWebhookToken: ${{ secrets.DISCORD_DOCS_DEPLOYED_WEBHOOK }}
        CommitMessage: ${{ github.event.commits[0].message }}
      run: |
        python WebhookSend.py


